title: schuyler.info
description: Technical projects, ideas, & solutions.
author: Schuyler Erle

social-network-links:
  github: schuyler
  bluesky: schuyler.info
  linkedin: sderle
  youtube: user/sderle
  soundcloud: schuyler-erle
  mastodon: metasocial.com/@schuyler
  rss: true

remote_theme: daattali/beautiful-jekyll

navbar-links:
  About: "about"

url: "https://schuyler.info"

avatar: /assets/img/underoos.jpg
favicon: /assets/img/favicon.png

date_format: "%-d %B %Y"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      reading_time: true
